version: "3"
services:
  nosql-db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db
  email:
    build:
      dockerfile: Dockerfile
      context: ./email
    container_name: email
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/email/node_modules

    env_file:
      - ./email/.env
  project:
    build:
      dockerfile: Dockerfile
      context: ./project
    container_name: project
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/project/node_modules
    env_file:
      - ./project/.env
  student:
    build:
      dockerfile: Dockerfile
      context: ./student
    container_name: student
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"

    volumes:
      - .:/app/
      - /app/student/node_modules
    env_file:
      - ./student/.env
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - email
      - project
      - student
    ports:
      - 80:80
